### ISSUE TITLE
Appirater Settings xml

### ISSUE THREAD

**Issue by baboog** [drewjw81/appirater-android#14]
Hi there
Could you please provide more detail how does appirater default settings in the xml work

appirator_days_until_prompt : 30
    appirator_launches_until_prompt: 15
      appirator_events_until_prompt : 15 

like for above settings, After 30 days of installation it will prompt? and what about the other two, 
Thanks

**Comment by drewjw81** [comment]
Super late on this... 
appirator_days_until_prompt is days after first launch until prompt
appirator_launches_until_prompt is number of launches until prompt
appirator_events_until_prompt is number of significant events until prompt. You need to trigger these your self by calling significantEvent

If any of these are met then the prompt will come up.
