### ISSUE TITLE
Can't be found in maven?

### ISSUE THREAD

**Issue by derjohng** [drewjw81/appirater-android#9]
I have tried to find the maven dependency in "Android Studio" with keyword "appirater". 
It seems not existed in maven repository?

**Comment by drewjw81** [comment]
Yeah, I'll get this done this weekend.  Been a bit distracted by the company I work for being purchased. Sorry for all the delays.

**Comment by IngmarStein** [comment]
Hi Drew, did you manage to upload the artifact to Maven Central?

**Comment by IngmarStein** [comment]
Any news?

**Comment by IngmarStein** [comment]
Hi Drew, any news here?

**Comment by kenyee** [comment]
weird that it's not in maven central but the description says to use it :-)

**Comment by kenyee** [comment]
ok...gave up and uploaded it to Maven Central.
You can add it as compile group: 'com.keysolutions', name: 'appirater-android', version: '1.4.0.0'
I also improved it a bit so it had all the things we needed for our project: https://github.com/kenyee/appirater-android
Package name is the same but API has changed so it's now called 1.4.

**Comment by dmsherazi** [comment]
great work @kenyee .. thanks

**Comment by drewjw81** [comment]
Closing this as I dropped the face of the earth. @kenyee do you want to connect to coordinate merging your branch in to mine and possibly moving this project to aa organization so I can let others work on this as well?
